name: video-shaper
static_sites:
  - name: web
    github:
      repo: samma/video-shaper
      branch: main
      deploy_on_push: true
    build_command: npm run build
    output_dir: build
    error_document: 404.html

